//TYPES PARA PROYECTOS

export const FORMULARIO_PROYECTO = 'FORMULARIO_PROYECTO'
export const LISTADO_PROYECTO = 'LISTADO_PROYECTO'
export const AGREGAR_PROYECTO = 'AGREGAR_PROYECTO'
export const MOSTRAR_ERROR = 'MOSTRAR_ERROR'
export const PROYECTO_ACTUAL = 'PROYECTO_ACTUAL'
export const ELIMINAR_PROYECTO  = 'ELIMINAR_PROYECTO'
export const PROYECTO_ERROR  = 'PROYECTO_ERROR'

// TYPES PARA TAREAS

export const TAREAS_PROYECTOS = 'TAREAS_PROYECTOS'
export const AGREGAR_TAREAS = 'AGREGAR_TAREAS'
export const ERROR_TAREA = 'ERROR_TAREA'
export const ELIMINAR_TAREA = 'ELIMINAR_TAREA'
export const ESTADO_TAREA = 'ESTADO_TAREA'
export const TAREA_ACTUAL = 'TAREA_ACTUAL'
export const EDITAR_TAREA = 'EDITAR_TAREA'

//TYPES PARA ALERTAS

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA'
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA'

// TYPES PARA REGISTRO DE USUARIOS
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO'
export const REGISTRO_ERROR = 'REGISTRO_ERROR'
export const OBTENER_USUARIO = 'OBTENER_USUARIO'
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const CERRAR_SESION = 'CERRAR_SESION'
